/**
 * PDF Generation utility for time entry records
 * Generates a simple PDF report with date, times, and work description
 */

import type { TimeEntry } from "@/lib/types";

// Simple PDF generation using jsPDF
export function generateEntryPDF(entry: TimeEntry, userName: string): Blob {
  // Dynamically import jsPDF to avoid SSR issues
  const { jsPDF } = require("jspdf");
  
  const doc = new jsPDF();
  
  // Set font
  doc.setFont("helvetica");
  
  // Title
  doc.setFontSize(22);
  doc.setTextColor(40, 40, 40);
  doc.text("Work Entry Report", 20, 25);
  
  // Date header with background
  doc.setFontSize(16);
  doc.setFillColor(66, 135, 245); // Blue background
  doc.setTextColor(255, 255, 255);
  doc.rect(15, 35, 180, 12, "F");
  doc.text(`Date: ${entry.date}`, 20, 43);
  
  // Entry details
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(12);
  
  let yPos = 60;
  
  // Time In/Out
  doc.setFont("helvetica", "bold");
  doc.text("Time In:", 20, yPos);
  doc.setFont("helvetica", "normal");
  doc.text(entry.timeIn || "Not specified", 60, yPos);
  
  yPos += 10;
  doc.setFont("helvetica", "bold");
  doc.text("Time Out:",  20, yPos);
  doc.setFont("helvetica", "normal");
  doc.text(entry.timeOut || "Not specified", 60, yPos);
  
  yPos += 15;
  
  // Work Description
  doc.setFont("helvetica", "bold");
  doc.text("Work Description:", 20, yPos);
  yPos += 8;
  
  doc.setFont("helvetica", "normal");
  const description = entry.workDescription || "No description provided";
  
  // Word wrap for long descriptions
  const splitText = doc.splitTextToSize(description, 170);
  doc.text(splitText, 20, yPos);
  
  yPos += (splitText.length * 7) + 15;
  
  // Leave/Holiday info (if applicable)
  if (entry.leave?.isLeave) {
    doc.setFont("helvetica", "bold");
    doc.text("Leave Information:", 20, yPos);
    yPos += 8;
    doc.setFont("helvetica", "normal");
    doc.text(`Type: ${entry.leave.leaveType || "Not specified"}`, 20, yPos);
    yPos += 7;
    if (entry.leave.leaveReason) {
      const reasonText = doc.splitTextToSize(`Reason: ${entry.leave.leaveReason}`, 170);
      doc.text(reasonText, 20, yPos);
      yPos += (reasonText.length * 7) + 10;
    }
  }
  
  if (entry.isHolidayWork) {
    doc.setFont("helvetica", "bold");
    doc.text("Holiday Work:", 20, yPos);
    yPos += 8;
    doc.setFont("helvetica", "normal");
    doc.text(`Category: ${entry.holidayCategory || "Not specified"}`, 20, yPos);
    yPos += 10;
  }
  
  // Footer
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated by ${userName}`, 20, 280);
  doc.text(`Generated on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`, 20, 286);
  
  // Return as Blob
  return doc.output("blob");
}

/**
 * Generate WhatsApp share link with pre-filled message
 * @param message - The message to pre-fill
 * @returns WhatsApp Web URL with encoded message
 */
export function getWhatsAppShareLink(message: string): string {
  return `https://wa.me/?text=${encodeURIComponent(message)}`;
}

/**
 * Download a PDF file
 * @param blob - The PDF blob to download
 * @param filename - The filename for the download
 */
export function downloadPDF(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}
